import { TestBed } from '@angular/core/testing';
import { BlueprintService } from './blueprint.service';
import { IBlueprintData } from './blueprint-types';
import { Step } from '~/solver/step';
import { rational } from '~/rational/rational';
import { Dataset } from '~/state/settings/dataset';


// Helper to decode base64 into a Uint8Array
function base64ToUint8Array(base64: string): Uint8Array {
  const binaryString = window.atob(base64);
  const len = binaryString.length;
  const bytes = new Uint8Array(len);
  for (let i = 0; i < len; i++) {
    bytes[i] = binaryString.charCodeAt(i);
  }
  return bytes;
}

// Helper to decode a blueprint string (handles version 0 zlib compression)
async function decodeFactorioBlueprint(bpString: string): Promise<IBlueprintData> {
  if (!bpString.startsWith('0')) {
    throw new Error('Only version 0 blueprints are supported in this test');
  }

  const base64Data = bpString.substring(1);
  const compressedBytes = base64ToUint8Array(base64Data);

  // Try zlib decompression first (for compressed blueprints from wiki/factorioprints)
  try {
    const ds = new DecompressionStream('deflate');
    const stream = new Blob([compressedBytes as any]).stream().pipeThrough(ds);
    const uncompressedText = await new Response(stream).text();
    return JSON.parse(uncompressedText) as IBlueprintData;
  } catch (e) {
    // If zlib fails, assume it's uncompressed (Factorio 2.0 uncompressed format)
    try {
      const jsonString = new TextDecoder('utf-8').decode(compressedBytes);
      return JSON.parse(jsonString) as IBlueprintData;
    } catch (e2) {
      throw new Error('Failed to decode blueprint string (neither compressed nor valid JSON)');
    }
  }
}

describe('BlueprintService', () => {
  let service: BlueprintService;

  beforeEach(() => {
    TestBed.configureTestingModule({});
    service = TestBed.inject(BlueprintService);
  });

  it('should be created', () => {
    expect(service).toBeTruthy();
  });

  describe('Decoding blueprints', () => {

    it('should decode a compressed Factorio blueprint string', async () => {
      // Sample compressed blueprint string generated for this test
      const compressedBpString = '0eJx9js0KgzAQhN9lzhEafwrmVUop0S52waxiolQk797EXnrqZWGWmY/vQDeuNC8sAeYA95N4mNsBz4PYMf/CPhMMOJCDgliXk/WeXDeyDIWz/YuFCo2owPKkN4yOdwWSwIHpyzvD/pDVdbSkwn+Swjz5NJ4kGyTgRWFPN2buaWJ+xBU2WvxZbq5lW7dtU9WlrnQZ4wfvD0qG';
      
      const bpData = await decodeFactorioBlueprint(compressedBpString);
      
      expect(bpData).toBeDefined();
      expect(bpData.blueprint).toBeDefined();
      expect(bpData.blueprint.item).toBe('blueprint');
      expect(bpData.blueprint.entities?.[0].name).toBe('assembling-machine-1');
    });

    it('should decode an uncompressed Factorio blueprint string (generated by BlueprintService)', async () => {
      // Create a sample blueprint data matching our models
      const data: IBlueprintData = {
        blueprint: {
          version: 562949953421312,
          item: 'blueprint',
          icons: [{ index: 1, signal: { type: 'item', name: 'assembling-machine-1' } }],
          entities: [{
            entity_number: 1,
            name: 'assembling-machine-1',
            position: { x: 0, y: 0 }
          }]
        }
      };

      // Encode using our service (which does 0 + base64(zlib(JSON)))
      const encodedString = await service.encodeBlueprintString(data);
      
      // Decode using the test helper
      const decodedData = await decodeFactorioBlueprint(encodedString);
      
      expect(decodedData).toBeDefined();
      expect(decodedData.blueprint.version).toBe(562949953421312);
      expect(decodedData.blueprint.item).toBe('blueprint');
      expect(decodedData.blueprint.entities?.[0].name).toBe('assembling-machine-1');
    });
  });

  describe('generateBlueprintFromSteps', () => {
    let mockData: any;

    beforeEach(() => {
      mockData = {
        machineRecord: {
          'assembling-machine-1': { size: [3, 3] },
          'assembling-machine-2(1)': { size: [3, 3] },
        },
        beaconRecord: {
          'beacon': { size: [3, 3] },
          'beacon(2)': { size: [3, 3] },
        }
      } as any;
    });

    it('should handle empty steps', async () => {
      const bp = await service.generateBlueprintFromSteps([], mockData);
      expect(bp).toBeTruthy();
    });

    it('should skip step with no machines or zero machines', async () => {
      const steps: Step[] = [
        { id: '1', machines: rational.zero },
        { id: '2' },
      ];
      const bp = await service.generateBlueprintFromSteps(steps, mockData);
      expect(bp).toContain('0e'); // base64 representation of basic JSON without entities
    });

    it('should skip step with no recipe or no machine settings', async () => {
      const steps: Step[] = [
        { id: '1', machines: rational.one, recipeId: undefined },
        { id: '2', machines: rational.one, recipeId: 'recipe', recipeSettings: undefined },
        { id: '3', machines: rational.one, recipeId: 'recipe', recipeSettings: { machineId: undefined } as any },
      ];
      const bp = await service.generateBlueprintFromSteps(steps, mockData);
      expect(bp).toContain('0e');
    });

    it('should handle empty modules array', async () => {
      const steps: Step[] = [
        {
          id: '1',
          itemId: 'iron-gear-wheel(2)',
          recipeId: 'iron-gear-wheel(1)',
          machines: rational(2),
          output: rational(10),
          recipeSettings: {
            machineId: 'assembling-machine-2(1)',
            modules: []
          } as any
        }
      ];

      const bp = await service.generateBlueprintFromSteps(steps, mockData);
      expect(bp).toBeTruthy();
    });

    it('should generate entities with qualities and beacons', async () => {
      const steps: Step[] = [
        {
          id: '1',
          itemId: 'iron-gear-wheel(2)',
          recipeId: 'iron-gear-wheel(1)',
          machines: rational(20),
          output: rational(10),
          recipeSettings: {
            machineId: 'assembling-machine-2(1)',
            modules: [
              { id: 'speed-module(3)', count: rational.one },
              { id: 'speed-module', count: rational.zero },
              { id: undefined, count: rational.one },
              { id: 'speed-module(2)', count: rational(2) } // Same baseId to trigger combination
            ],
            beacons: [
              { id: 'beacon(2)', count: rational(20), modules: [{ id: 'productivity-module', count: rational(2) }] },
              { id: 'beacon', count: rational.zero },
              { id: undefined, count: rational.one }
            ]
          } as any
        }
      ];

      const bp = await service.generateBlueprintFromSteps(steps, mockData);
      
      // Decode it back to verify the contents
      const decoded: IBlueprintData = await decodeFactorioBlueprint(bp);

      expect(decoded.blueprint.icons[0].signal.name).toBe('iron-gear-wheel');
      expect(decoded.blueprint.entities?.length).toBe(40); // 20 machines + 20 beacons
      
      const machineEntity = decoded.blueprint.entities?.find(e => e.name === 'assembling-machine-2');
      expect(machineEntity?.quality).toBe('uncommon');
      expect(machineEntity?.recipe_quality).toBe('uncommon');
      
      const beaconEntity = decoded.blueprint.entities?.find(e => e.name === 'beacon');
      expect(beaconEntity?.quality).toBe('rare');
    });

    it('should handle edge cases for layout and beacons', async () => {
      const steps: Step[] = [
        {
          id: '1',
          recipeId: 'iron-gear-wheel',
          machines: rational(20), // 20 machines to trigger machine wrapping
          recipeSettings: {
            machineId: 'assembling-machine-1',
            beacons: [
              { count: rational(1) }, // Ignored because no id
              { id: 'beacon', count: rational.zero }, // Should be ignored
              { id: 'beacon', count: rational(20) } // No 'total' property, 20 beacons to trigger leftover rows
            ]
          } as any
        },
        {
          id: '2',
          recipeId: 'copper-cable',
          machines: rational(1),
          recipeSettings: {
            machineId: 'assembling-machine-1',
            beacons: [
              { id: 'beacon', count: rational.zero } // All beacons ignored
            ]
          } as any
        },
        {
          id: '3',
          recipeId: 'transport-belt',
          machines: rational(1), // Must be > 0 so the step isn't skipped
          recipeSettings: {
            machineId: 'assembling-machine-1',
            beacons: [
              { id: 'fake-beacon-id', count: rational(2) } // Fake ID triggers size ?? 3 fallback
            ]
          } as any
        }
      ];

      const bp = await service.generateBlueprintFromSteps(steps, mockData);
      const decoded: IBlueprintData = await decodeFactorioBlueprint(bp);
      
      expect(decoded.blueprint.entities?.length).toBe(44); // 40 (step 1) + 1 (step 2) + 3 (step 3)
    });

    it('should handle step with no output and empty modules', async () => {
      const steps: Step[] = [
        {
          id: '1',
          itemId: 'iron-plate',
          recipeId: 'iron-plate',
          machines: rational(1),
          output: rational.zero, // no output to force fallback to steps[0]
          recipeSettings: {
            machineId: 'assembling-machine-1',
            modules: [] // empty modules
          } as any
        }
      ];

      const bp = await service.generateBlueprintFromSteps(steps, mockData);
      expect(bp).toBeTruthy();
    });
    it('should assign correct inventory index and distinct stacks for modules', async () => {
      const steps: Step[] = [
        {
          id: '1',
          recipeId: 'lab-science',
          machines: rational(1),
          recipeSettings: {
            machineId: 'lab',
            modules: [
              { id: 'speed-module', count: rational(2) },
              { id: 'productivity-module', count: rational(1) }
            ]
          } as any
        },
        {
          id: '2',
          recipeId: 'mining',
          machines: rational(1),
          recipeSettings: {
            machineId: 'electric-mining-drill',
            modules: [
              { id: 'speed-module', count: rational(1) }
            ]
          } as any
        },
        {
          id: '3',
          recipeId: 'pump',
          machines: rational(1),
          recipeSettings: {
            machineId: 'pumpjack',
            modules: [
              { id: 'speed-module', count: rational(1) }
            ]
          } as any
        },
        {
          id: '4',
          recipeId: 'no-size',
          machines: rational(1),
          recipeSettings: {
            machineId: 'no-size',
            modules: [
              { id: 'zero-count', count: rational.zero } // covers plan.length === 0
            ],
            beacons: [
              { id: 'no-size-beacon', count: rational.one, modules: [{ id: 'zero', count: rational.zero }] }
            ]
          } as any
        }
      ];

      const customMockData = {
        machineRecord: {
          'lab': { size: [3, 3] },
          'electric-mining-drill': { size: [3, 3] },
          'pumpjack': { size: [3, 3] },
          'no-size': {}, // Covers falling back to size 3
        },
        beaconRecord: {
          'no-size-beacon': {}
        }
      } as any;

      const bp = await service.generateBlueprintFromSteps(steps, customMockData);
      const decoded: IBlueprintData = await decodeFactorioBlueprint(bp);

      const labEntity = decoded.blueprint.entities?.find(e => e.name === 'lab');
      expect(labEntity?.items).toBeDefined();
      expect((labEntity?.items as any[])?.length).toBe(2);
      
      const speedModPlan = (labEntity?.items as any[])?.find(i => i.id.name === 'speed-module');
      expect(speedModPlan?.items?.in_inventory?.length).toBe(2);
      expect(speedModPlan?.items?.in_inventory?.[0].inventory).toBe(3); // Lab inventory
      expect(speedModPlan?.items?.in_inventory?.[0].stack).toBe(0);
      expect(speedModPlan?.items?.in_inventory?.[1].stack).toBe(1);

      const prodModPlan = (labEntity?.items as any[])?.find(i => i.id.name === 'productivity-module');
      expect(prodModPlan?.items?.in_inventory?.length).toBe(1);
      expect(prodModPlan?.items?.in_inventory?.[0].stack).toBe(2); // Next stack index

      const drillEntity = decoded.blueprint.entities?.find(e => e.name === 'electric-mining-drill');
      expect((drillEntity?.items as any[])?.[0].items?.in_inventory?.[0].inventory).toBe(2); // Drill inventory
    });
  });
});
